DROP TABLE IF EXISTS oauth_client_details;

CREATE TABLE oauth_client_details (
  client_id varchar(256) NOT NULL,
  resource_ids varchar(256) DEFAULT NULL,
  client_secret varchar(256) DEFAULT NULL,
  scope varchar(256) DEFULT NULL,
  authorized_grant_types varchar(256) DEFAULT NULL,
  web_server_redirect_uri varchar(256) DEFAULT NULL,
  authorities varchar(256) DEFAULT NULL,
  access_token_validity int(11) DEFAULT NULL,
  refresh_token_validity int(11) DEFAULT NULL,
  additional_information varchar(4096) DEFAULT NULL,
  autoapprove varchar(4096) DEFAULT NULL,
  PRIMARY KEY (client_id)
);


INSERT INTO oauth_client_details(client_id, resource_ids, client_secret, scope, authorized_grant_types, authorities, access_token_validity, refresh_token_validity)
VALUES ('harmeet', 'rest_api', '$2a$11$gxpnezmYfNJRYnw/EpIK5Oe08TlwZDmcmUeKkrGcSGGHXvWaxUwQ2', 'trust,read,write', 'client_credentials,authorization_code,implicit,password,refresh_token', 'ROLE_USER', '4500', '45000');

  DROP TABLE IF EXISTS oauth_access_token;

  CREATE TABLE oauth_access_token (
  token_id varchar(256) DEFAULT NULL,
  token blob,
  authentication_id varchar(256) DEFAULT NULL,
  user_name varchar(256) DEFAULT NULL,
  client_id varchar(256) DEFAULT NULL,
  authentication blob,
  refresh_token varchar(256) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS oauth_refresh_token;

CREATE TABLE oauth_refresh_token (
  token_id varchar(256) DEFAULT NULL,
  token blob,
  authentication blob
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- MySQL Script generated by MySQL Workbench
-- Sáb 30 Mai 2015 13:33:09 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mo409
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mo409` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mo409` ;

-- -----------------------------------------------------
-- Table `mo409`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`ALUNO` (
  `ra` INT NOT NULL,
  PRIMARY KEY (`ra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`PROFESSOR` (
  `ra` INT NOT NULL,
  PRIMARY KEY (`ra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`USUARIO` (
  `idUSUARIO` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(80) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `ALUNO_ra` INT NOT NULL,
  `PROFESSOR_ra` INT NOT NULL,
  PRIMARY KEY (`idUSUARIO`, `ALUNO_ra`, `PROFESSOR_ra`),
  INDEX `fk_USUARIO_ALUNO1_idx` (`ALUNO_ra` ASC),
  INDEX `fk_USUARIO_PROFESSOR1_idx` (`PROFESSOR_ra` ASC),
  CONSTRAINT `fk_USUARIO_ALUNO1`
    FOREIGN KEY (`ALUNO_ra`)
    REFERENCES `mo409`.`ALUNO` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_ra`)
    REFERENCES `mo409`.`PROFESSOR` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`DISCIPLINA` (
  `idDISCIPLINA` INT NOT NULL,
  PRIMARY KEY (`idDISCIPLINA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`TURMA` (
  `idTURMA` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `DISCIPLINA_idDISCIPLINA` INT NOT NULL,
  PRIMARY KEY (`idTURMA`, `DISCIPLINA_idDISCIPLINA`),
  INDEX `fk_TURMA_DISCIPLINA1_idx` (`DISCIPLINA_idDISCIPLINA` ASC),
  CONSTRAINT `fk_TURMA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_idDISCIPLINA`)
    REFERENCES `mo409`.`DISCIPLINA` (`idDISCIPLINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`ALUNO_has_TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`ALUNO_has_TURMA` (
  `ALUNO_ra` INT NOT NULL,
  `TURMA_idTURMA` INT NOT NULL,
  PRIMARY KEY (`ALUNO_ra`, `TURMA_idTURMA`),
  INDEX `fk_ALUNO_has_TURMA_TURMA1_idx` (`TURMA_idTURMA` ASC),
  INDEX `fk_ALUNO_has_TURMA_ALUNO1_idx` (`ALUNO_ra` ASC),
  CONSTRAINT `fk_ALUNO_has_TURMA_ALUNO1`
    FOREIGN KEY (`ALUNO_ra`)
    REFERENCES `mo409`.`ALUNO` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_has_TURMA_TURMA1`
    FOREIGN KEY (`TURMA_idTURMA`)
    REFERENCES `mo409`.`TURMA` (`idTURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`TURMA_has_PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`TURMA_has_PROFESSOR` (
  `TURMA_idTURMA` INT NOT NULL,
  `PROFESSOR_ra` INT NOT NULL,
  PRIMARY KEY (`TURMA_idTURMA`, `PROFESSOR_ra`),
  INDEX `fk_TURMA_has_PROFESSOR_PROFESSOR1_idx` (`PROFESSOR_ra` ASC),
  INDEX `fk_TURMA_has_PROFESSOR_TURMA1_idx` (`TURMA_idTURMA` ASC),
  CONSTRAINT `fk_TURMA_has_PROFESSOR_TURMA1`
    FOREIGN KEY (`TURMA_idTURMA`)
    REFERENCES `mo409`.`TURMA` (`idTURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TURMA_has_PROFESSOR_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_ra`)
    REFERENCES `mo409`.`PROFESSOR` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`AULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`AULA` (
  `idAULA` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NULL,
  `hora_fim` TIME NULL,
  `data` DATE NULL,
  `TURMA_idTURMA` INT NOT NULL,
  PRIMARY KEY (`idAULA`, `TURMA_idTURMA`),
  INDEX `fk_AULA_TURMA1_idx` (`TURMA_idTURMA` ASC),
  CONSTRAINT `fk_AULA_TURMA1`
    FOREIGN KEY (`TURMA_idTURMA`)
    REFERENCES `mo409`.`TURMA` (`idTURMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`PRESENCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`PRESENCA` (
  `numero_ticks` INT NULL,
  `aprovado` TINYINT(1) NULL,
  `idPRESENCA` INT NOT NULL,
  `ALUNO_ra` INT NOT NULL,
  PRIMARY KEY (`idPRESENCA`, `ALUNO_ra`),
  INDEX `fk_PRESENCA_ALUNO1_idx` (`ALUNO_ra` ASC),
  CONSTRAINT `fk_PRESENCA_ALUNO1`
    FOREIGN KEY (`ALUNO_ra`)
    REFERENCES `mo409`.`ALUNO` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`PROFESSOR_has_DISCIPLINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`PROFESSOR_has_DISCIPLINA` (
  `PROFESSOR_ra` INT NOT NULL,
  `DISCIPLINA_idDISCIPLINA` INT NOT NULL,
  PRIMARY KEY (`PROFESSOR_ra`, `DISCIPLINA_idDISCIPLINA`),
  INDEX `fk_PROFESSOR_has_DISCIPLINA_DISCIPLINA1_idx` (`DISCIPLINA_idDISCIPLINA` ASC),
  INDEX `fk_PROFESSOR_has_DISCIPLINA_PROFESSOR1_idx` (`PROFESSOR_ra` ASC),
  CONSTRAINT `fk_PROFESSOR_has_DISCIPLINA_PROFESSOR1`
    FOREIGN KEY (`PROFESSOR_ra`)
    REFERENCES `mo409`.`PROFESSOR` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESSOR_has_DISCIPLINA_DISCIPLINA1`
    FOREIGN KEY (`DISCIPLINA_idDISCIPLINA`)
    REFERENCES `mo409`.`DISCIPLINA` (`idDISCIPLINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mo409`.`TICKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mo409`.`TICKS` (
  `idTICKS` INT NOT NULL AUTO_INCREMENT,
  `ALUNO_ra` INT NOT NULL,
  `hora` DATETIME NOT NULL,
  `distancia` INT UNSIGNED NOT NULL,
  `PRESENCA_idPRESENCA` INT NOT NULL,
  `PRESENCA_ALUNO_ra` INT NOT NULL,
  PRIMARY KEY (`idTICKS`, `ALUNO_ra`, `PRESENCA_idPRESENCA`, `PRESENCA_ALUNO_ra`),
  INDEX `fk_TICKS_ALUNO1_idx` (`ALUNO_ra` ASC),
  INDEX `fk_TICKS_PRESENCA1_idx` (`PRESENCA_idPRESENCA` ASC, `PRESENCA_ALUNO_ra` ASC),
  CONSTRAINT `fk_TICKS_ALUNO1`
    FOREIGN KEY (`ALUNO_ra`)
    REFERENCES `mo409`.`ALUNO` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TICKS_PRESENCA1`
    FOREIGN KEY (`PRESENCA_idPRESENCA` , `PRESENCA_ALUNO_ra`)
    REFERENCES `mo409`.`PRESENCA` (`idPRESENCA` , `ALUNO_ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Banco de dados: `mo409`
--

--
-- Fazendo dump de dados para tabela `ALUNO`
--

INSERT INTO `ALUNO` (`ra`) VALUES
(161255);

--
-- Fazendo dump de dados para tabela `ALUNO_has_TURMA`
--

INSERT INTO `ALUNO_has_TURMA` (`ALUNO_ra`, `TURMA_idTURMA`) VALUES
(161255, 1);

--
-- Fazendo dump de dados para tabela `AULA`
--

INSERT INTO `AULA` (`idAULA`, `hora_inicio`, `hora_fim`, `data`, `TURMA_idTURMA`) VALUES
(1, '10:00:00', '12:00:00', '2015-05-14', 1);

--
-- Fazendo dump de dados para tabela `DISCIPLINA`
--

INSERT INTO `DISCIPLINA` (`idDISCIPLINA`) VALUES
(1);

--
-- Fazendo dump de dados para tabela `PRESENCA`
--

INSERT INTO `PRESENCA` (`numero_ticks`, `aprovado`, `idPRESENCA`, `ALUNO_ra`) VALUES
(4, 1, 0, 161255),
(4, 1, 1, 161255);

--
-- Fazendo dump de dados para tabela `PROFESSOR`
--

INSERT INTO `PROFESSOR` (`ra`) VALUES
(122222);

--
-- Fazendo dump de dados para tabela `PROFESSOR_has_DISCIPLINA`
--

INSERT INTO `PROFESSOR_has_DISCIPLINA` (`PROFESSOR_ra`, `DISCIPLINA_idDISCIPLINA`) VALUES
(122222, 1);

--
-- Fazendo dump de dados para tabela `TICKS`
--

INSERT INTO `TICKS` (`idTICKS`, `ALUNO_ra`, `hora`, `distancia`, `PRESENCA_idPRESENCA`, `PRESENCA_ALUNO_ra`) VALUES
(1, 161255, '2015-05-15 06:04:31', 0, 1, 161255),
(2, 161255, '2015-05-15 06:04:31', 1, 1, 161255);

--
-- Fazendo dump de dados para tabela `TURMA`
--

INSERT INTO `TURMA` (`idTURMA`, `nome`, `DISCIPLINA_idDISCIPLINA`) VALUES
(0, 'A', 1),
(1, 'A', 1);

--
-- Fazendo dump de dados para tabela `TURMA_has_PROFESSOR`
--

INSERT INTO `TURMA_has_PROFESSOR` (`TURMA_idTURMA`, `PROFESSOR_ra`) VALUES
(1, 122222);

--
-- Fazendo dump de dados para tabela `USUARIO`
--

INSERT INTO `USUARIO` (`idUSUARIO`, `nome`, `sobrenome`, `email`, `login`, `senha`, `ALUNO_ra`, `PROFESSOR_ra`) VALUES
(4, 'lucas carvalho', NULL, 'lucas.carvalho@ic.unicamp.br', 'lucascarvalho', 'senha', 161255, 122222),
(5, 'eliane martins', NULL, 'eliane@ic.unicamp.br', 'eliane', 'senha', 161255, 122222);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

